export enum AppActions {
    REQUEST_WEBAPP = "REQUEST_WEBAPP",
    RECEIVE_WEBAPP = "RECEIVE_WEBAPP",
    REQUEST_MODULES = "REQUEST_MODULES",
    RECEIVE_MODULES = "RECEIVE_MODULES",
    REQUEST_SAVE = "REQUEST_SAVE",
    RECEIVE_SAVE = "RECEIVE_SAVE",
    REQUEST_CREATE = "REQUEST_CREATE",
    RECEIVE_CREATE = "RECEIVE_CREATE",
    REQUEST_DELETE = "REQUEST_DELETE",
    RECEIVE_DELETE = "RECEIVE_DELETE",
    UPDATE_FILE_STATE = "UPDATE_FILE_STATE",
    UPDATE_APP_DATA = "UPDATE_APP_DATA",
}